// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBay_LZcr0vaYM6f3V0hxvROPZoFCrgm4I',
    appId: '1:570838199630:web:4b2ff3fa216f15aca4821f',
    messagingSenderId: '570838199630',
    projectId: 'galerysaya-4550c',
    authDomain: 'galerysaya-4550c.firebaseapp.com',
    storageBucket: 'galerysaya-4550c.firebasestorage.app',
    measurementId: 'G-S6WPBCM6MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgtj6PmuMnRtvOljaWGOSNocc-OkUp3mw',
    appId: '1:570838199630:android:0a80555d80cc19cea4821f',
    messagingSenderId: '570838199630',
    projectId: 'galerysaya-4550c',
    storageBucket: 'galerysaya-4550c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb0qlM2klvDkGcIigd2MojGscB3gZN6Ss',
    appId: '1:570838199630:ios:f0707bf6a73f7a68a4821f',
    messagingSenderId: '570838199630',
    projectId: 'galerysaya-4550c',
    storageBucket: 'galerysaya-4550c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb0qlM2klvDkGcIigd2MojGscB3gZN6Ss',
    appId: '1:570838199630:ios:f0707bf6a73f7a68a4821f',
    messagingSenderId: '570838199630',
    projectId: 'galerysaya-4550c',
    storageBucket: 'galerysaya-4550c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNYv8c8YQwbOJdeULgSSWDw-pPwpOc5XM',
    appId: '1:570838199630:web:d25931d0bc844b7ba4821f',
    messagingSenderId: '570838199630',
    projectId: 'galerysaya-4550c',
    authDomain: 'galerysaya-4550c.firebaseapp.com',
    storageBucket: 'galerysaya-4550c.firebasestorage.app',
    measurementId: 'G-0C215XBSLL',
  );

}